name: OTA update
on:
  push:
    branches:
      - main

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout repository
        uses: actions/checkout@v3      
      
      - name: Read and update iteration number
        id: update_iteration
        run: |
          CURRENT_ITERATION=$(grep -oP 'versionnumber = \K\d+' versions)
          UPDATED_ITERATION=$((CURRENT_ITERATION + 1))
          sed -i "s/versionnumber = $CURRENT_ITERATION/versionnumber = $UPDATED_ITERATION/" versions
          echo "ITERATION=$UPDATED_ITERATION" >> $GITHUB_ENV

      - name: Get version and commit info
        run: |
          VERSION=$(node -e "console.log(require('./package.json').version)")
          COMMIT_HASH=$(git rev-parse --short HEAD)
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          ITERATION=${{ steps.update_iteration.outputs.iteration }}

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add versions
          git commit -m "Update versionnumber to $UPDATED_ITERATION"
          git push origin HEAD:${{ github.ref }}
